# Generated by Django 5.1.4 on 2024-12-06 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestParamsToOpenWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('request_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'request_params_to_openweather',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResponseFromOpenWeather',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('weather', models.CharField(max_length=255)),
                ('temperature', models.IntegerField()),
                ('feels_like', models.IntegerField()),
                ('wind_speed', models.FloatField()),
                ('response_time', models.DateTimeField()),
            ],
            options={
                'db_table': 'response_from_openweather',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_first_time', models.BooleanField(default=True)),
                ('language', models.CharField(default='RU', max_length=2)),
                ('units', models.CharField(
                    choices=[('standard', 'Как на физике'), ('metric', 'Метрическая'), ('imperial', 'Имперская')],
                    default='metric', max_length=8)),
                ('instruction_on_start', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_preferences',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='UserRequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255, null=True)),
                ('is_current_location', models.BooleanField(default=False)),
                ('counter', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_request_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='RequestResponseConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                              to='weather_console.requestparamstoopenweather')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                               to='weather_console.responsefromopenweather')),
                ('user_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                                   to='weather_console.userrequesthistory')),
            ],
            options={
                'db_table': 'request_response_connection',
                'managed': True,
            },
        ),
    ]
